---
title: "crash-20201112-221544-av2902-lap_tmpl-d667fd47-bddf-4296-8776-65c7020565e5.pklz"
slug: "crash-20201112-221544-av2902-lap_tmpl-d667fd47-bddf-4296-8776-65c7020565e5.pklz"
categories: [files]
author: Anna Vannucci
date: 2020-11-16
---
```BASH
resting_preproc_sub-026_ses-3.anat_preproc_niworkflows_ants_0.anat_preproc_niworkflows_ants_0_skullstrip.anat_skullstrip_ants.lap_tmpl
```
```Python
Traceback (most recent call last):

  File "/usr/local/miniconda/lib/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)

FileNotFoundError: [Errno 2] No such file or directory: '/outputs/tmp/resting_preproc_sub-026_ses-3/anat_preproc_niworkflows_ants_0/anat_preproc_niworkflows_ants_0_skullstrip/anat_skullstrip_ants/lap_tmpl/_0xdff2077e42c097e3a3c18048e6f4551b_unfinished.json' -> '/outputs/tmp/resting_preproc_sub-026_ses-3/anat_preproc_niworkflows_ants_0/anat_preproc_niworkflows_ants_0_skullstrip/anat_skullstrip_ants/lap_tmpl/_0xdff2077e42c097e3a3c18048e6f4551b.json'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 480, in run
    hashfile_unfinished.replace('_unfinished', ''))

  File "/usr/local/miniconda/lib/python3.7/shutil.py", line 580, in move
    copy_function(src, real_dst)

  File "/usr/local/miniconda/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)

  File "/usr/local/miniconda/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:

FileNotFoundError: [Errno 2] No such file or directory: '/outputs/tmp/resting_preproc_sub-026_ses-3/anat_preproc_niworkflows_ants_0/anat_preproc_niworkflows_ants_0_skullstrip/anat_skullstrip_ants/lap_tmpl/_0xdff2077e42c097e3a3c18048e6f4551b_unfinished.json'
```